### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by mitsaravanan** [mitsaravanan/SEBC#10]

**Comment by mitsaravanan** [comment]
167  yum -y install krb5-server krb5-libs krb5-auth-dialog krb5-workstation
  168  sudo yum -y install krb5-workstation krb5-libs krb5-auth-dialog
  169  vim /var/kerberos/krb5kdc/kdc.conf
  170  vim /etc/krb5.conf
  171  cat /etc/krb5.conf
  172  clear
  173  cat /etc/krb5.conf
  174  vim /etc/krb5.conf
  175  /usr/sbin/kdb5_util create -s
  176  pwd
  177  ls
  178  ls -ltr
  179  vim /var/kerberos/krb5kdc/kdc.conf
  180  vim /var/kerberos/krb5kdc/kdc.conf
  181  vim /etc/krb5.conf
  182  /usr/sbin/kdb5_util create -s
  183  kadmin.local
  184  clear
  185  vim /var/kerberos/krb5kdc/kadm5.acl
  186  kadmin.local
  187  service krb5kdc start
  188  service kadmin start

**Comment by mitsaravanan** [comment]
Enable Kerberos for Cluster 1
Congratulations!
You have enabled Kerberos for all your cluster(s).

Cluster Status
Cluster 1   Successfully enabled Kerberos.

**Comment by mfernest** [comment]
Completed.
