### ISSUE TITLE
HDFS Tested

### ISSUE THREAD

**Issue by mitsaravanan** [mitsaravanan/SEBC#11]

**Comment by mitsaravanan** [comment]
Command to run teragen
time hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-0.20-mapreduce/hadoop-examples.jar teragen -Ddfs.block.size=67108864 5120000000 /user/christie/tgen64

**Comment by mitsaravanan** [comment]
Output of the time command

``` sh
real    14m26.029s
user    0m8.290s
sys     0m0.499s
```

**Comment by mitsaravanan** [comment]
drwxr-xr-x   - christie christie          0 2016-09-23 15:00 /user/christie/tgen64/_temporary
[root@ip-172-31-6-157 krb5kdc]# hadoop fs -ls /user/christie/tgen64/_temporary

**Comment by mitsaravanan** [comment]
drwxr-xr-x   - christie christie          0 2016-09-23 15:00 /user/christie/tgen64/_temporary
[root@ip-172-31-6-157 krb5kdc]# hadoop fs -ls /user/christie/tgen64/_temporary

**Comment by mitsaravanan** [comment]
The HDFS test completed

**Comment by mfernest** [comment]
Completed
