### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by mitsaravanan** [mitsaravanan/SEBC#2]
Storage labs for Cloudera training day-2

**Comment by mitsaravanan** [comment]
# Storage labs

Goals of the lab are
- Replicate data to another cluster
- Use teragen and terasort to benchmark performance
- Enable HA for the NameNode

**Comment by mitsaravanan** [comment]
- The location of hadoop jar file is /opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hadoop-mapreduce
- The command to generate file using teragen is sudo -u hdfs  hadoop jar /opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen 500000000 /tmp/mitsaravanan

**Comment by mitsaravanan** [comment]
- The replicating the partner file errored due to the issue - Caused by: java.net.UnknownHostException: ip-10-67-0-30.ec2.internal

**Comment by mitsaravanan** [comment]
- The server is not in the same zone to communicate and it was doisucssed with the instructor and a known issue.

**Comment by mitsaravanan** [comment]
Got the following mesages while enabling HA in the cluster.
- Configure the HDFS Web Interface Role of Hue service(s) Hue to be an HTTPFS role instead of a NameNode. Documentation
- For each of the Hive service(s) Hive, stop the Hive service, back up the Hive Metastore Database to a persistent store, run the service command "Update Hive Metastore NameNodes", then restart the Hive services.
- Both were addressed using the link http://www.cloudera.com/documentation/manager/5-0-x/Cloudera-Manager-Managing-Clusters/cm5mc_hdfs_hi_avail.html

**Comment by mitsaravanan** [comment]
Completed configuring HA for HDFS

**Comment by mitsaravanan** [comment]
Ading users and role assignments for users
- mitsaravanan has been assigend Full Administrator role with cloudera as the password
- admin has been assigned Limited Operator role

**Comment by mfernest** [comment]
Completed. 👍
