### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by mitsaravanan** [mitsaravanan/SEBC#3]

**Comment by mitsaravanan** [comment]
Allocation - 25% to HDFS and 75% to YARN completed and cluster restarted.

**Comment by mitsaravanan** [comment]
**mapreduce.jobs.maps calculation**

``` sh
$ yarn.nodemanager.resource.memory-mb       111616
$ mapreduce.map.memory.mb                   1024
$ yarn.nodemanager.resource.cpu-vcores      64
$ mapreduce.map.cpu.vcores                  1
$ number of physical drives                 12
$ workload factor                           2
$ number of worker nodes                    10
```

``` sh
$ mapreduce.jobs.maps=MIN(yarn.nodemanager.resource.memory-mb / mapreduce.map.memory.mb,yarn.nodemanager.resource.cpu-vcores / mapreduce.map.cpu.vcores, number of physical drives x workload factor) x number of worker nodes
$ mapreduce.jobs.maps=240

@mitsaravanan -- the usual answer is between 112-120, depending how you calculate. Looks like you have a stray multiplier in here somewhere.
```

**Comment by mitsaravanan** [comment]
**YARN/RM Lab: Doing the Math**

The yarn cluster sizing has been completed and the final excel is uploaded at resources/labs/0_YarnCalcs.xlsx.

The details are also given above for reference.

**Comment by mitsaravanan** [comment]
**YARN/RM Lab: Static Service Pools**
The HDFS and YARN resources were allocated and the screenshot attached at resources/labs/1_static_pools.png

**Comment by mitsaravanan** [comment]
**YARN/RM Lab: Tuning for YARN**
- The time command used to capture -  time -f "\t%e Elapsed Real Time (secs)"

**Comment by mitsaravanan** [comment]
- sudo time -f "\t%e Elapsed Real Time (secs)" sh -xv YARNtest.sh

**Comment by mitsaravanan** [comment]
The output is
`Testing loop ended on Wed Sep 21 20:25:26 EDT 2016 :  88.41 Elapsed Real Time (secs)
`

**Comment by mitsaravanan** [comment]
command to run YARNtest is  **time sudo sh -xv YARNtest.sh**

**Comment by mitsaravanan** [comment]
container memory - 512 1024 - The slowest timings observed.

``` sh
real    1m28.407s
user    0m40.643s
sys     0m1.779s
```

**Comment by mitsaravanan** [comment]
container memory - 512 6144 - The medium timings observed.

``` sh
real    1m0.929s
user    0m38.066s
sys     0m1.717s
```

**Comment by mitsaravanan** [comment]
container memory - 1024 8192- The fastest timings observed.

``` sh
real    1m0.166s
user    0m36.572s
sys     0m1.634s
```

@mitsaravanan - what do you figure is the key factor from improved response time?

**Comment by mitsaravanan** [comment]
Lab completed and all exercise materials uploaded into GIT

**Comment by mfernest** [comment]
Completed -- solid work.
