### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by mitsaravanan** [mitsaravanan/SEBC#4]

**Comment by mitsaravanan** [comment]
sudo yum -y install krb5-server krb5-libs krb5-auth-dialog krb5-workstation
sudo yum -y install krb5-workstation krb5-libs krb5-auth-dialog

**Comment by mitsaravanan** [comment]
Edit sudo vim /var/kerberos/krb5kdc/kdc.conf on Master node

**Comment by mitsaravanan** [comment]
sudo vim /etc/krb5.conf
[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = MITSARAVANAN.COM
 dns_lookup_realm = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true
 rdns = false

# default_realm = EXAMPLE.COM

 default_ccache_name = KEYRING:persistent:%{uid}
 udp_preference_limit = 1
 default_tgs_enctypes = arcfour-hmac
 default_tkt_enctypes = arcfour-hmac

[realms]
MITSARAVANAN.COM = {
  kdc = ip-172-31-1-193.us-west-2.compute.internal
  admin_server = ip-172-31-1-193.us-west-2.compute.internal
 }

[domain_realm]
 .example.com = MITSARAVANAN.COM
 example.com = MITSARAVANAN.COM

**Comment by mitsaravanan** [comment]
sudo /usr/sbin/kdb5_util create -s

**Comment by mitsaravanan** [comment]
[ec2-user@ip-172-31-1-193 yarn-perf]$ sudo /usr/sbin/kdb5_util create -s
Loading random data
Initializing database '/var/kerberos/krb5kdc/principal' for realm 'MITSARAVANAN.COM',
master key name 'K/M@MITSARAVANAN.COM'
You will be prompted for the database Master Password.
It is important that you NOT FORGET this password.
Enter KDC database master key:
Re-enter KDC database master key to verify:

**Comment by mitsaravanan** [comment]
[ec2-user@ip-172-31-1-193 yarn-perf]$ sudo kadmin.local
Authenticating as principal root/admin@MITSARAVANAN.COM with password.
kadmin.local:  addprinc cloudera-scm@MITSARAVANAN.COM
WARNING: no policy specified for cloudera-scm@MITSARAVANAN.COM; defaulting to no policy
Enter password for principal "cloudera-scm@MITSARAVANAN.COM":
Re-enter password for principal "cloudera-scm@MITSARAVANAN.COM":
Principal "cloudera-scm@MITSARAVANAN.COM" created.

**Comment by mitsaravanan** [comment]
[ec2-user@ip-172-31-1-193 lib]$ beeline
2016-09-22 16:25:54,656 WARN  [main] mapreduce.TableMapReduceUtil: The hbase-prefix-tree module jar containing PrefixTreeCodec is not present.  Continuing without it.
Beeline version 1.1.0-cdh5.8.0 by Apache Hive
beeline> !connect jdbc:hive2://54.213.151.182:10000/default;principal=hive/ip-172-31-1-193.us-west-2.compute.internal@MITSARAVANAN.COM
scan complete in 3ms
Connecting to jdbc:hive2://54.213.151.182:10000/default;principal=hive/ip-172-31-1-193.us-west-2.compute.internal@MITSARAVANAN.COM
Enter username for jdbc:hive2://54.213.151.182:10000/default;principal=hive/ip-172-31-1-193.us-west-2.compute.internal@MITSARAVANAN.COM: sentryadmin
Enter password for jdbc:hive2://54.213.151.182:10000/default;principal=hive/ip-172-31-1-193.us-west-2.compute.internal@MITSARAVANAN.COM: ********
Connected to: Apache Hive (version 1.1.0-cdh5.8.0)
Driver: Hive JDBC (version 1.1.0-cdh5.8.0)
Transaction isolation: TRANSACTION_REPEATABLE_READ
0: jdbc:hive2://54.213.151.182:10000/default> show tables;
INFO  : Compiling command(queryId=hive_20160922162626_8bba014a-0277-4fb8-9796-75b9811db0c7): show tables
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:tab_name, type:string, comment:from deserializer)], properties:null)
INFO  : Completed compiling command(queryId=hive_20160922162626_8bba014a-0277-4fb8-9796-75b9811db0c7); Time taken: 0.774 seconds
INFO  : Executing command(queryId=hive_20160922162626_8bba014a-0277-4fb8-9796-75b9811db0c7): show tables
INFO  : Starting task [Stage-0:DDL] in serial mode
INFO  : Completed executing command(queryId=hive_20160922162626_8bba014a-0277-4fb8-9796-75b9811db0c7); Time taken: 0.234 seconds
INFO  : OK
+-----------+--+
| tab_name  |
+-----------+--+
+-----------+--+
No rows selected (2.325 seconds)
0: jdbc:hive2://54.213.151.182:10000/default>

**Comment by mfernest** [comment]
Completed.
