### ISSUE TITLE
Hue

### ISSUE THREAD

**Issue by mitsaravanan** [mitsaravanan/SEBC#5]

**Comment by mitsaravanan** [comment]
got error while running the command - sudo build/env/bin/hue useradmin_sync_with_unix

``` sh
, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/cloudera/parcels/CDH-5.8.0-1.cdh5.8.0.p0.42/lib/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/backends/sqlite3/base.py", line 347, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file

```

@mitsaravanan - do you recall if you were using sqllite3 or MySQL for your datastore?

**Comment by mitsaravanan** [comment]
HUE 
getent group | grep hadoop

export all the variables below to work.
sudo HUE_DATABASE_PASSWORD=hue HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=1  JAVA_HOME=/usr/java/jdk1.7.0_67-cloudera HUE_SECRET_KEY=admin HUE_CONF_DIR=/var/run/cloudera-scm-agent/process/224-hue-HUE_SERVER /opt/cloudera/parcels/CDH/lib/hue/build/env/bin/hue useradmin_sync_with_unix

export HUE_CONF_DIR="/var/run/cloudera-scm-agent/process/`ls -alrt /var/run/cloudera-scm-agent/process | grep HUE | tail -1 | awk '{print $9}'`"

**Comment by mitsaravanan** [comment]
The LB hue configuration had an error.

**Comment by mfernest** [comment]
Your issues may have stemmed in part from using Hue's default database, which is quite flaky.

Incomplete
