### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by mitsaravanan** [mitsaravanan/SEBC#9]

**Comment by mitsaravanan** [comment]
Installation in progress
wget https://archive.cloudera.com/cm5/redhat/7/x86_64/cm/cloudera-manager.repo
cp cloudera-manager.repo  /etc/yum.repos.d/
sudo yum install oracle-j2sdk1.7
http://54.218.106.85:7180

CREATE USER 'cm'@'ip-172-31-6-157.us-west-2.compute.internal' IDENTIFIED BY 'cm';

grant all privileges on cm.\* to 'cm'@'ip-172-31-6-157.us-west-2.compute.internal' identified by 'cm';

**Comment by mitsaravanan** [comment]
The CDH and Hue installed

**Comment by mitsaravanan** [comment]
Command and output for hdfs dfs -ls /user
[root@ip-172-31-6-157 cloudera-scm-server]# hadoop fs -ls /user
Found 7 items
drwxr-xr-x   - hdfs   supergroup          0 2016-09-23 12:06 /user/christie
drwxr-xr-x   - hdfs   supergroup          0 2016-09-23 12:01 /user/hdfs
drwxrwxrwx   - mapred hadoop              0 2016-09-23 11:53 /user/history
drwxrwxr-t   - hive   hive                0 2016-09-23 11:54 /user/hive
drwxrwxr-x   - hue    hue                 0 2016-09-23 11:55 /user/hue
drwxrwxr-x   - oozie  oozie               0 2016-09-23 11:55 /user/oozie
drwxr-xr-x   - hdfs   supergroup          0 2016-09-23 12:07 /user/weiner

Command and output for hadoop classpath
[root@ip-172-31-6-157 cloudera-scm-server]# hadoop classpath
/etc/hadoop/conf:/opt/cloudera/parcels/CDH-5.7.3-1.cdh5.7.3.p0.5/lib/hadoop/libexec/../../hadoop/lib/_:/opt/cloudera/parcels/CDH-5.7.3-1.cdh5.7.3.p0.5/lib/hadoop/libexec/../../hadoop/.//_:/opt/cloudera/parcels/CDH-5.7.3-1.cdh5.7.3.p0.5/lib/hadoop/libexec/../../hadoop-hdfs/./:/opt/cloudera/parcels/CDH-5.7.3-1.cdh5.7.3.p0.5/lib/hadoop/libexec/../../hadoop-hdfs/lib/_:/opt/cloudera/parcels/CDH-5.7.3-1.cdh5.7.3.p0.5/lib/hadoop/libexec/../../hadoop-hdfs/.//_:/opt/cloudera/parcels/CDH-5.7.3-1.cdh5.7.3.p0.5/lib/hadoop/libexec/../../hadoop-yarn/lib/_:/opt/cloudera/parcels/CDH-5.7.3-1.cdh5.7.3.p0.5/lib/hadoop/libexec/../../hadoop-yarn/.//_:/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/lib/_:/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/.//_

**Comment by mfernest** [comment]
Completed.
